plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  instance-state-name: running
keyed-groups:
  - key: tags.Name
    prefix: name
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"

