- name: k8s setup 
  connection: amazon.aws.aws_ssm
  hosts: name_agent
  vars_files:
    - secrets.yml
    - vars.yml
  roles:
    #- awscli
    #- kubectl
    #- install_helm_argo
    - docker
    - install_java
 




