- name: k8s setup 
  connection: amazon.aws.aws_ssm
  hosts: all
  vars:
    ec2_name: "{{ ec2_tags.Name | default('ubuntu-node') }}"
  roles:
    #- awscli
    #- kubectl
    #- install_helm_argo
    - docker
    - install_java
 




