$ANSIBLE_VAULT;1.1;AES256
61616439303364366565383162653462656133363236646363613032616232643833376338653032
6239636538336638343965386331666537393363363935660a383263363137633138653831353538
39666138363965396239623335613064663061656131366335633337653538666239303238613664
6338383530626233300a343837343033346232336535643262353761363463383966636133613961
30366261303738376439613837383464353337373034653761353066656164383066333331326630
63643866633832306232396532616230656231313530646330346231303663336130343335363232
34326465343838663034303739326263613461303563316431626535646466353935373564386231
61313934323665363162383233666663316561613532356365386263613336306266373735393937
6233
