name: 'Terraform or Ansible'
run-name: ${{inputs.action}}
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Please Select The Command To Run { plan , apply, destroy }'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
          - ansible
permissions:
  contents: read
  id-token: write
jobs:
  Terraform:
    if: ${{ inputs.action != 'ansible' }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::101561167685:role/githubrolev
        aws-region: eu-north-1
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Terraform Init
      run: terraform init --var-file=var.tfvars
      working-directory: terraform
    - name: Terraform Plan
      if: ${{ inputs.action == 'plan' }}
      run: terraform plan --var-file=var.tfvars
      working-directory: terraform
    - name: Terraform Apply
      if: ${{ inputs.action == 'apply' }}
      run: terraform apply -auto-approve --var-file=var.tfvars
      working-directory: terraform
    - name: Terraform Destroy
      if: ${{ inputs.action == 'destroy' }}

  ansible:
    if: ${{ inputs.action == 'ansible' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::101561167685:role/githubrolev
          aws-region: eu-north-1
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml
      run: terraform destroy -auto-approve --var-file=var.tfvars
      working-directory: terraform
